# Validates JSON schema and data using Node module.
# https://github.com/ajv-validator/ajv-cli
name: Validate JSONs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://nhalstead00/validate-json-action:latest
        env:
          INPUT_SCHEMA: /data/schema.json
          INPUT_JSONS: /data/sermons.json